### ISSUE TITLE
Covariates in diffSplice (multi-factor design)

### ISSUE THREAD

**Issue by adomingues** [comprna/SUPPA#138]
Hi @EduEyras, 

is it possible to add covariates in `diffSplice`? Something like one would do for differential gene expression controlling for example for sex in a comparison with human samples, `~ condition + sex` (http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#multi-factor-designs)

I am assuming this is not possible otherwise it would stated somewhere, but I want to make sure.

Cheers-

**Comment by adomingues** [comment]
Thank you. For the moment I wont need it, turns out it won't be useful for the dataset I am analysing, but it's good to know it would be possible. I will keep it mind for the future. 

Cheers,
António

**Comment by akgolebiewski** [comment]
Hi, 

Could you elaborate on how to incorporate covariates into the model?

Thank you!
Anna

**Comment by EduEyras** [comment]
In the lm function in R to perform linear regression, you can include a vector with the value of your covariables, e.g. sex, age, dataset, etc...

Here are some examples on how to do that
https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/adding-covariates-to-a-linear-model.html

I hope this helps

E.
