### ISSUE TITLE
No reading tpm file

### ISSUE THREAD

**Issue by willems533** [comprna/SUPPA#14]
Hey, 

After following the steps in the manual I seem to have a reading error of my TPM file, though its in the correct format. 
Command is: python3 /usr/local/lib/python3.5/dist-packages/SUPPA/suppa.py psiPerEvent -e tpm/WT-T.txt -i gtf/merged_RI_strict.ioe -o psi/WT-T_RI

ERROR:lib.tools:87303, in line 87304. Skipping line...
ERROR:lib.tools:87304, in line 87305. Skipping line...
ERROR:psiCalculator:No expression values have been buffered.
ERROR:psiCalculator:Unknown error: 1

Would this have to do with an incorrect install of a certain package or?

Thanks in advance

**Comment by EduEyras** [comment]
Hi Willem,
let me know if you managed to fix this. It could be that the IDs are not exactly the same, or that some of the IDs in the ioe do not have expression value calculated. 

Can you send us a sample of the .tpm and .ioe files?

best

E.
