### ISSUE TITLE
Why this regions were not regarded as RI ?

### ISSUE THREAD

**Issue by gouwei1** [comprna/SUPPA#150]
As the figure:
![1](https://user-images.githubusercontent.com/90610419/196909435-6f78516d-d348-4f11-a82f-725116926eb4.png)

**Comment by EduEyras** [comment]
Hi,

thanks for the question.
The default definition of RI in SUPPA is quite restrictive and it assumes
one single intron:

----###-------###----
----##########----

So these multi-intron retention are not picked up

If you use the option -b V ("variable boundary") the external boundary
constraints are dropped. You can also
allow some variability of the exon boundary matches with -t (please see
options).
That could work in this case

I hope this helps

Eduardo

**Comment by gouwei1** [comment]
That solved my problem. Thank you!
