### ISSUE TITLE
Can't compute PSI whereas MAJIQ can do

### ISSUE THREAD

**Issue by lmanchon** [comprna/SUPPA#16]
--Hi,

the main problem in SUPPA is if one or more transcripts of the event do not appear in the expression file
we can't compute PSI, whereas in MAJIQ we do. 
For example, for my gene of interest i have 4 transcripts, Salmon quantify only 3 of them, then SUPPA can't compute PSI on my gene!
Is there any option to permit the computation even if one transcript isn't quantified ?

Thank you --

**Comment by JLTrincado** [comment]
Hi,

there is an option at the time of running the differential splicing analysis:

- nan | --nan-threshold: Percentage allowed of samples per condition with nan values for returning a DeltaPSI (Default: 0, no missing values allowed).

This option allows you to define a threshold in which SUPPA2 will calculate a value for a given event. By default is 0 (that means, no missing values are allowed). Let's say you want to relax this filter and let SUPPA to get values for your events that at least have half of the samples informed (per condition). You would raise this flag to 0.5.

Let me know if you have any problems running the software with this option.

Thanks again for your interest.
Best,

**Comment by lmanchon** [comment]
okay, thank you.
i'm going to try that.
best.

**Comment by EduEyras** [comment]
There are in general many differences between genome-mapped reads and how reads are assigned by Salmon that will explain the discrepancies you observe. 

If you have evidence that the transcript is really expressed, you can also do the following:

Add a small value to every transcript TPM, e.g. TPM_i <--- TPM_i + 0.01
Renormalize TPM values: TPM_i <--- 10^6 TPM_i / ( SUM_k TPM_k )
Now you have non-zero values for all transcripts and TPMs add up to 10^6, and you will be able to get PSI for all events.

Alternatively, and perhaps more correctly, you could add  1 read count to every transcript, and then calculate the TPMs from them. TPMs will be then properly normalized per length.

The main issue here is whether the transcript is not enough expressed for Salmon to see it, or it is an error of the quantification. If the transcript is very lowly expressed, you should see also that from reads mapped to the genome. In general, such case will be highly variable across reps, and not a trustable PSI. What's the posterior given by MAJIQ for that event?

I hope this helps
best

Eduardo
