### ISSUE TITLE
No replicate samples

### ISSUE THREAD

**Issue by gengbaobao** [comprna/SUPPA#168]
Hello developers

In my dataset, I don't have enough replicate samples. I mean I just have one sampe in my control group and 3 samples in  treatment group. Could I run the "suppa.py diffSplice" function? How should I set the paramenters?

Best,

**Comment by EduEyras** [comment]
Hi, without replicates it will be difficult to apply the diffSplice methods

However, you can perform other tests comparing each PSI from the one
control sample to the PSIs from the three samples in the other condition.

Any test that assesses how much the control sample differs from the
distribution described by the other group.

However, you would usually test it the opposite way, one treatment sample
vs a distribution of controls, as treatments effects can be variable, and
you want the control group to represent a healthy population.

I hope it helps

Eduardo
