### ISSUE TITLE
about nan values

### ISSUE THREAD

**Issue by fafuyyk** [comprna/SUPPA#176]
Hello!
I recently started trying to use SUPPA2 for ASE analysis, and then I found that a large number of nan values appeared in my psi results. I would like to ask whether these nan values need to be removed. And how to deal with these nan values of psi when doing difffSplice?

**Comment by EduEyras** [comment]
Hi,

You can manage the use of nan cases with the -nan option.
Please see
https://github.com/comprna/SUPPA#command-and-options-1

They cannot be used, but if you have enough samples per condition, you can
use events that have some nan cases and control how many nan's are allowed.

I hope this helps

Thanks for using SUPPA

Eduardo
