### ISSUE TITLE
U12 splicing event

### ISSUE THREAD

**Issue by jiehuichen** [comprna/SUPPA#180]
Dear SUPPA team,

I'm very interested in U12 splicing events, I wonder if you will include U12 analysis in SUPPA?

By the way, based on your expertise, which algorithm can be used to analyze U12 splicing currently?

Thanks a lot.

Best,
Jiehui

**Comment by jiehuichen** [comment]
Hi Eduardo,

I appreciate your suggestions.

I found there are some U12 databases listed in Intron Annotation and Orthology Database (IAOD).
https://introndb.lerner.ccf.org/sitepages/downloads/

About the analysis of U12 splicing in mice RNA-seq by SUPPA, is it reasonable to take the "GRCm38_U12.bed" file listed on the website as the annotation (may need to convert it to GTF format)?

https://introndb.lerner.ccf.org/static/bed/GRCm38_U12.bed



Thanks a lot.


Jiehui

**Comment by EduEyras** [comment]
Hi Jiehui,

SUPPA operates with a GTF file with the full annotation.

If you're only interested in the alternative splicing of U12 introns, you
could first calculate all AS events, and then check which ones overlap with
your U12 intron dataset.

Best

Eduardo

**Comment by jiehuichen** [comment]
Thanks a lot. It helps.

Best,
Jiehui
