### ISSUE TITLE
Error with  diffSplice

### ISSUE THREAD

**Issue by Tang-pro** [comprna/SUPPA#186]
Hi, @leipzig 
When I run the following code
`suppa.py diffSplice --method empirical --input Gbar.ioe --psi psi/3-79_fiber_20dpa.txt psi/3-79_fiber_25dpa.txt --tpm tpm/3-79_fiber_20dpa.txt tpm/3-79_fiber_25dpa.txt -o fiber25dpavsfiber20dpa --lower-bound 0.2 -gc`

This error message was generated
ERROR:__main__:Unknown error: (<class 'UnboundLocalError'>, UnboundLocalError("cannot access local variable 'i' where it is not associated with a value"), <traceback object at 0x2ac4488ccdc0>)

How to solve it, please

**Comment by gnilihzeux** [comment]
Have you solved this problem? I am facing the same issue.

**Comment by Tang-pro** [comment]
@gnilihzeux 
Check whether the column name of the txt file is correct, and it seems that the first column cannot have spaces. It has been so long that I have forgotten it, but it is certain that the format of the input file does not match.

**Comment by EduEyras** [comment]
Thanks
Yes, that would be an important thing to check
E.

**Comment by gnilihzeux** [comment]
Thanks. 
I have conducted a thorough check and it seems that this is not the cause of the issue.
I had raised another issue #189
