### ISSUE TITLE
Help about rank differential gene

### ISSUE THREAD

**Issue by BourbonZhang** [comprna/SUPPA#187]
Dear SUPPA2 Development Team,

I am researching the differences in alternative splicing of certain genes among different subtypes of breast cancer, hence I need to filter out genes with significant differences across various subtypes.

After conducting differential analysis of evnet and isoform (diffSplice), I obtained their respective .dpsi files, which contain many genes with p-values less than 0.05. How should I rank the results of events and isoforms to obtain a gene ranking?

Best regards and keep up the good work,
Bourbon

**Comment by EduEyras** [comment]
Hi,

Thanks for your question.

If I understand correctly, you want to select those cases that are likely
more relevant in separating the subtypes.

You could do something analogous to what one does with differential gene
expression when obtaining a ranking to use for e.g. gene set enrichment
analysis.

You could use the value deltaPSI * ( - 1) * log10(p-value)

This will give you a rank with the extreme positive values being the more
significant increases in PSI and extreme negative values being the more
significant reductions in PSI.

Alternatively you can use |deltaPSI| * (-1) * log10(p-value)
This will rank by significant change regardless of the direction.

Was something like this what you had in mind?

best

Eduardo

**Comment by BourbonZhang** [comment]
Hi Eduardo,

Thank you very much for your answer; it indeed covers one aspect of what I wanted to know.

An even more important point I want to know is that a gene has some events psi and isoforms psi. The previous method you told me can only select one of them. I want to know, how can I combine both to review the status of a gene comprehensively?

For example, 

for gene A, 
event1 has a value of |deltaPSI| * (-1) * log10(p-value) = 5,
event2 = 4, 
isoform1 = 3, 
isoform2 = 2, 
soform3 = 1. 

For gene B, 
event1 = 2, 
event2 = 3, 
isoform1 = 4, 
isoform2 = 6. 

How should I compare these?

best，
Bourbon

**Comment by BourbonZhang** [comment]
Hi Eduardo,

Thank you very much for your answer, these contents are very helpful to me.

best,
Bourbon
