### ISSUE TITLE
How to Determine Differential Variable Splicing Events (DAS)?

### ISSUE THREAD

**Issue by happypiggyzjx** [comprna/SUPPA#192]
Dear SUPPA2 development team:

Thank you for developing such a convenient and fast software. I have a problem when analyzing the data: how does SUPPA2 determine that a variable clipping event is a difference variable clipping event? By reading our documentation and published literature, can I understand that as long as **0.05 ≤ PSI ≤ 0.95 and |ΔPSI| > 0.2,** the event is considered to be a differential variable clipping event for the two samples used for comparison?

Can you please give the judgment criteria for DAS systematically? Thank you and sincerely look forward to your professional reply.

happypiggy

**Comment by EduEyras** [comment]
The actual criteria for differential splicing is based on a statistical test comparing the differences between conditions with the distribution of differences between replicates (in the empirical method) or by comparing the differences between two conditions directly (classical). The conditions on PSI and deltaPSI can be changed and adapted to the specific problem. PSI does not need to be of any particular value. In general we found that |deltaPSI| > 0.2 is a reasonable threshold. But what threshold to choose exactly can be estimated through the statistical test. 

I hope this helps

Eduardo
