### ISSUE TITLE
suppa version issue

### ISSUE THREAD

**Issue by happypiggyzjx** [comprna/SUPPA#195]
Hi,
Eduardo

I am using the software you developed for some time now, and today I suddenly realized that the version has been updated to 2.4, but in README.md, the pip download command is still: pip install SUPPA==2.3

I checked your update to README.md and found that this line was changed, but nothing actually changed. While wondering if this is due to a clerical error, I tried the command: pip install SUPPA==2.4 and got the following error:

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement SUPPA==2.4 (from versions: 2.2, 2.2.1, 2.2.2, 2.3)
ERROR: No matching distribution found for SUPPA==2.4

Does this mean that the latest version is still 2.3 or should I just copy the latest version 2.4 from github?

Best,
happypiggy

**Comment by EduEyras** [comment]
I am not sure pip is working well 

Please use a clone or download of the current code in github. That should work fine.

Thanks

E.

**Comment by nalcala** [comment]
Hi, 

I am having the same issue, pip does not find version 2.4, and the readme still does not refer to 2.4 . I understand that that we can install it from this repo, but is it possible to make what is necessary to have it accessible on pip? It is much simpler and also makes it possible for example to automatically install it with conda recipes for instance.

Thanks

Nicolas

**Comment by EduEyras** [comment]
Hi

We'll look into this. The student who added the previous version to PIP
already moved onto other things.

For now, please use the version 2.4 from the github, as it fixes a bug from
the previous version.

Thanks

Eduardo
