### ISSUE TITLE
ClusterEvent problem

### ISSUE THREAD

**Issue by Xing-2024** [comprna/SUPPA#197]
Hi, 

I met the following data problem:
command in local event model:
suppa.py clusterEvents --dpsi diff_output_DSL_unpaired_FL_AL --psivec diff_output_DSL_unpaired_FL_AF.psivec --sig-threshold 0.05 --eps 0.05 --min-pts 20 --groups 1-4,5-8 -o diff_DSL_FL_AF_cluster

ERROR:lib.cluster_tools:Unknown error: (<class 'ValueError'>, ValueError('Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.'), <traceback object at 0x155537468a40>)

the command works well in the transcript model:
suppa.py clusterEvents --dpsi diff_output_DTU_unpaired.dpsi --psivec diff_output_DTU_unpaired.psivec --sig-threshold 0.05 --eps 0.05 --min-pts 20 --groups 1-4,5-8 -o diff_DTU_cluster
Succeed.

I compared the dpsi and psivec files in the both commands, and the formats are nearly the same, but run failed in the first command. weird. 

Any suggestion?

thank you.

**Comment by EduEyras** [comment]
Sorry I could not reply earlier

Did you solve this?

How different are the files?

It looks like there might be a format issue triggering the error

E.
