### ISSUE TITLE
Can't find inclusion_transcripts in ioe file

### ISSUE THREAD

**Issue by mianlee** [comprna/SUPPA#200]
Dear author :

When tried to generate ioe file, for the header of ioe file, I didn't find inclusion_transcripts , instead it is  alternative_transcripts? Did I do wrong?

Best
Mian

**Comment by EduEyras** [comment]
Hi
The iow file should have a column for the transcripts that include the exon
(or exon fragment) and a column that includes all transcripts that include
or skip the exon (with the specific intron boundary constraints).
Does this answer your question?
E
