### ISSUE TITLE
Extract TPM from Salmon dictionary.iteritems()

### ISSUE THREAD

**Issue by Ekomshiro** [comprna/SUPPA#23]
Hello,
I'm trying to follow the tutorial but I found a problem with your script to extract TPM from Salmon output.
It seems to call dictionary.iteritems(), which fails.
In fact the function iteritems() is renamed items() in Python3

**Comment by JLTrincado** [comment]
Hi!

Are you refering about multipleFiledSelection script? We updated this time ago for adapting it to python3. In fact, in this script we have the following lines:

    for key, value in [(x,y) for x, y in dictionary.items() if x != "header"]:

Did you download the latest release?Maybe you0re using an old one.

Thanks!
Best,

**Comment by Ekomshiro** [comment]
Hi,
I started looking into SUPPA last week and used pip to install SUPPA.
pip show SUPPA
gives the version as 2.2.1

**Comment by JLTrincado** [comment]
Hi again,

yes you were right. The pip installation is pointing to an older version of SUPPA. While we are updating this, please download directly the latest version in the "Releases" section.

Thanks for your comment,
