### ISSUE TITLE
Memory leak in diffSplice / significanceCalculator.py

### ISSUE THREAD

**Issue by uniqueg** [comprna/SUPPA#4]
Hi again,

I'm currently running hundreds of individual diffSplice comparisons and I have realized that for big datasets, i.e. comparisons with many replicates in one or both of the conditions, diffSplice is killed because it runs out of memory.

For most comparisons, I have less than 100 replicates in total, and 3 Gb seem to be sufficient for these cases. But as soon as the total number of replicates is higher than ~100-150, memory requirements start going through the roof. For comparisons involving a condition with 414 replicates (single cell dataset), I needed close to 100Gb of memory (and a looooot of patience for empirical P value calculation ;-).

This was on human data with ~110k transcripts and analyzing ~20k skipped exon events. The total combined size of the input files (tpm, psi & ioe files) is <500 Mb. Not surprisingly, when analyzing less events and/or less transcripts, the problem appears less dramatic, although I haven't really tried to look at it systematically. In any case, it appears to me that the way in which memory requirements scale with replicate number/transcripts/events is exponential, and I cannot really see why that would need to be the case...

If you like, I could provide you with some input files in order to replicate the issue, although I would imagine that you should not have any problem replicating the issue with your own super-sized expression and psi tables (perhaps randomly merged).

Best,
Alex

**Comment by JLTrincado** [comment]
HI Alex,

which method are you using for the diffSplice? the "empirical" or the "classical"? I assume that you are using the empirical, which is true that for big datasets like yours requires an important amount of memory. We recommend you to use the classical method. It applies Wilcoxon rank-sum test, or signed-rank test if the data is paired. The drawback is that classical test does not take into account the variability across replicates. We also recommend you to correct for multiple testing, with the -gc option.

We are really interested in knowing how works SUPPA with single cell data. Let us know how it was.

Thanks again for your interest and best,
Juanlu

**Comment by uniqueg** [comment]
Hi Juanlu,

indeed I am using the _empirical_ mode (with gene correction), and I guess I would like to stick with that mode, precisely because it takes into account variability across replicates - which is, arguably, of fundamental importance when analyzing single cell data.

In any case, running diffSplice in this manner is not a problem for me, since I do have access to a HPC cluster that can handle these kind of requirements. I just wanted to report the issue I ran into in order to ensure that you are aware of it and, possibly, improve/solve it by code refactoring. Because (and I may be wrong here) the excessive memory usage does not seem to me to be a necessity of the algorithm itself, but rather a side effect of its implementation, i.e. more of a classic _memory leak_. Of course, it is probably not an issue many users will run into and thus may, understandably, not be on top of your priority list...

With regard to the single cell analysis: I am actually doing a meta analysis of many different RNA-Seq studies concerned with one common process. Among these studies, only one has single cell data and is not actually treated any differently from other studies. Transcript and gene level abundances, as well as their changes along the process of interest, seem to be very robust though, both within the replicates of each condition and between different conditions, and that includes the single cell data as well. So although I am not in a position where I can draw any specific conclusions on diffSplice's performance/accuracy on single cell data (or on my use case in general), I would expect that given the robustness of transcript abundance estimates, it should perform reasonably well. If I happen to get any more insights here, I will let you know.

Best regards and keep up the good work,
Alex

**Comment by EduEyras** [comment]
Hi Alex,

thanks for the message. We'll try to improve the implementation to avoid this kind of situation. As you say it is avoidable and we may not need to measure all possible variations. Also a point to be able to expand comparisons ad-hoc with many samples per condition.

We're also trying suppa with single cell data and the only issue is the dropouts. On those samples we see many more transcripts with no expression or very little expression, which may not be consistent across clones. We're looking into ways to avoid that. If you have data from multiple clones, perhaps you can either impute or filter out transcripts without consistent expression in a condition. So far that's what we're trying.

cheers

E.

**Comment by uniqueg** [comment]
Thanks Eduardo, that sounds reasonable. Do you rescale TPMs after adjustments/filtering?

**Comment by EduEyras** [comment]
Hi,

In principle we don't re-scale, since we recalculate the TPMs from scratch with the new filtered transcriptome. We've tried before to do the rescale but the result wasn't very good.
E.

**Comment by uniqueg** [comment]
I see. Thanks a lot!

**Comment by esebesty** [comment]
Hi all, we still see this issue.

```
Calculating differential analysis between conditions: Hyperdiploid_PSI_per_local_events_2023-05-30 and Non_Hyperdiploid_PSI_per_local_events_2023-05-30
suppa-diff_splicing_valid_cohort_2023-05-30.sh: line 20: 11303 Killed python3.6 /disk/work/shared/tools/SUPPA/suppa.py diffSplice --method empirical --input "/disk/work/users/gb1/pediatric_ALL-RNA_seq_analysis/data/suppa_intermediates/filtered_ioe/generate_events_ALL_filtered_2022-10-13.ioe" --psi "${input_folder}/Hyperdiploid_PSI_per_local_events_2023-05-30.psi" "${input_folder}/Non_Hyperdiploid_PSI_per_local_events_2023-05-30.psi" --tpm "${input_folder}/Hyperdiploid_transcript_expression_file_2023-05-30" "${input_folder}/Non_Hyperdiploid_transcript_expression_file_2023-05-30" --area 1000 --lower-bound 0.05 -gc -o "${output_folder}/Hyperdiploidy_AS_events-2023-05-30"
Calculating differential analysis between conditions: ETV6RUNX1_PSI_per_local_events_2023-05-30 and Non_ETV6RUNX1_PSI_per_local_events_2023-05-30
suppa-diff_splicing_valid_cohort_2023-05-30.sh: line 30: 11416 Killed
```

We always have a few hundred samples in one condition and 50-200 in the other. Any suggestions on how to solve the memory leak, besides moving to a machine with much more memory?

**Comment by EduEyras** [comment]
Hi Endre!
with so many samples, the --method empirical is not very efficient. But the
--method classical would be effective. Have you tried it? It is a Wilcoxon
unpaired test, so it should be ok with an unbalanced number of samples.
I hope this helps
E.
