### ISSUE TITLE
dpsi file for Cluster analysis

### ISSUE THREAD

**Issue by bioysu** [comprna/SUPPA#42]
Here is the example of dpsi file for clustser analysis:
Cond1_Cond2_dPSI  Cond1_Cond2_p-val Cond2_Cond3_dPSI  Cond2_Cond3_p-val
event1    <dpsi_value>    <dpsi_value>    <dpsi_value>    <dpsi_value>
event2    <dpsi_value>    <dpsi_value>    <dpsi_value>    <dpsi_value>
event3    <dpsi_value>    <dpsi_value>    <dpsi_value>    <dpsi_value>
The header is dPSI and p-value, but the matrix only includes <dpsi_value>, could you tell me whether p-value is needed? And why Cond1_Cond3_dPSI is not included?

I have 4 conditions, I also want to known how to order the columns of dpsi file for cluster analysis.

**Comment by EduEyras** [comment]
Hi, 
You can also do an all against all comparison. This is something you can select on the command line.

For clustering SUPPA uses events that have a significant change in at least one comparison, so the pvalues are looked at for that.

JC or JL can perhaps confirm

Cheers

E


Dr. Eyras
ICREA Research Professor
Universitat Pompeu Fabra
Barcelona
Spain

**Comment by JLTrincado** [comment]
Yes,  that's correct.  SUPPA uses events that have a significant change in at least one comparison. The output from the diffSplice step is ready for being used for the clustering, so there is no need to order the columns

For performing a pairwise comparison between each pair of adjacent conditions, you should indicate in the command line --combination or -c.

Thanks for your interest in our software.
Best
