### ISSUE TITLE
diffSplice returns an error please help

### ISSUE THREAD

**Issue by screadore** [comprna/SUPPA#61]
I'm trying to calculate a Mann Whitney U value for these RNA sequences with survival rate. I got the code to work slightly, but it keeps giving me the error. "RuntimeWarning: divide by zero encountered in double_scalars z = (bigu - meanrank) / sd" 

It says this is the code that is causing the issue...

`   if alternative is None:
        warnings.warn("Calling `mannwhitneyu` without specifying "
                      "`alternative` is deprecated.", DeprecationWarning)

    x = np.asarray(x)
    y = np.asarray(y)
    n1 = len(x)
    n2 = len(y)
    ranked = rankdata(np.concatenate((x, y)))
    rankx = ranked[0:n1]  # get the x-ranks
    u1 = n1*n2 + (n1*(n1+1))/2.0 - np.sum(rankx, axis=0)  # calc U for x
    u2 = n1*n2 - u1  # remainder is U for y
    T = tiecorrect(ranked)
    if T == 0:
        raise ValueError('All numbers are identical in mannwhitneyu')
    sd = np.sqrt(T * n1 * n2 * (n1+n2+1) / 12.0)

    meanrank = n1*n2/2.0 + 0.5 * use_continuity
    if alternative is None or alternative == 'two-sided':
        bigu = max(u1, u2)
    elif alternative == 'less':
        bigu = u1
    elif alternative == 'greater':
        bigu = u2
    else:
        raise ValueError("alternative should be None, 'less', 'greater' "
                         "or 'two-sided'")

    z = (bigu - meanrank) / sd
    if alternative is None:
        # This behavior, equal to half the size of the two-sided
        # p-value, is deprecated.
        p = distributions.norm.sf(abs(z))
    elif alternative == 'two-sided':
        p = 2 * distributions.norm.sf(abs(z))
    else:
        p = distributions.norm.sf(z)

    u = u2
    # This behavior is deprecated.
    if alternative is None:
        u = min(u1, u2)
    return MannwhitneyuResult(u, p)

RanksumsResult = namedtuple('RanksumsResult', ('statistic', 'pvalue'))`

**Comment by EduEyras** [comment]
The Wilcoxon and Mann-Whitney tests we implemented in SUPPA handles this exception and it should probably catch that case:

In lib/diff_tools.py

        except:
            # Wilcoxon fails when the two vectors given are identical, even if the number of reps is enough
            # For those cases we decided to give a pval of 1.0
            pval = 1.0
            event_lst.append(i)
            uncorrected_pvals.append(pval)

Where is the code that you mention?

Thanks

E.
