### ISSUE TITLE
Differential splicing of polyadenylation sites

### ISSUE THREAD

**Issue by JamalEH** [comprna/SUPPA#77]
Dear Eduardo,

SUPPA2 is able to quantify and report alternative last (AL) exon events, which is good, since the last exons are always the target of several factors such as miRNAs and regulators of mRNA stability and transport. But, what about alternative polyadenylation (pA) sites? Would it be possible to also include this feature in SUPPA2 script as well, if the input TPM files allow for this of course? if so, SUPPA2 will be the package that detects the most possible binary splicing events (excluding non-binary or complex events).

Thank you!

Kind regards,
Jamal.

**Comment by EduEyras** [comment]
Thanks Jamal,
We have not developed much that aspect. 
We hope to work more on that in the future in the context of long-read sequencing
best
Eduardo
