### ISSUE TITLE
AS locus info from miscellaneous AS types (AF and AL) present simultaneously in one specific ioe file 

### ISSUE THREAD

**Issue by HaoZhang17** [comprna/SUPPA#9]
Dear developers,

I found this when I was trying to extract the locus information from the ioe files generated for different event types. Just like the figure shows, in the ioe file specific for the "AF" type (red and blue rectangles), there is information that does not belong to this type (green rectangle). It seems like this info belongs to the "AL" type, rather than the "AF" type. Likewise,  info from the "AF" type was found to present in the ioe file specifically for the "AL" type.
![image](https://user-images.githubusercontent.com/30916517/31897274-7863044e-b7db-11e7-9f4d-30d128518ed0.png)

I want to know whether this was set deliberately or not. Thanks!

Sincerely,

Hao Zhang

**Comment by EduEyras** [comment]
Hi Hao Zhang,
Could you please provide more information? Why do you consider they do not correspond to AF events? 

I can see for example in the blue case that the coordinates of the first exon changes, and this is why it including two almost identical events. Is that what you mean? The definitions for some events is strict for some of the exon boundaries, so as soon as there is one exon with a variable splice-site, you start getting multiple almost identical cases. 

You can use the variable boundary option ( -b V ) which allows to relax some of the exon boundaries in the definitions. This will merge into a single event these cases. Please have a look at the definitions here https://github.com/comprna/SUPPA to see whether the -b V option could improve this. 

I hope this helps

Eduardo
